version: '3.7'

services:
  web:
    build: .
    command: python /books/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/books
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    environment:
      POSTGRES_DB: db
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
